namespace: ibmce
name: ocp_ansible
version: 1.0.0
readme: README.md
authors:
  - Eric Kleinsorgen <emk@us.ibm.com>
description: DevOps Ansible Collection
license:
  - EPL-2.0
tags:
  - ibmce
  - mvie
  - rhocp
dependencies:
  "kubernetes.core": ">=3.0.0"
  "community.general": ">=5.6.0"
  "ansible.utils": ">=5.1.2"
repository: https://github.com/ekleinso/ansible-devops
documentation: https://github.com/ekleinso/ansible-devops
homepage: https://github.com/ekleinso/ansible-devops
issues: https://github.com/ekleinso/ansible-devops/issues
build_ignore: []

