
- name: Create the StorageCluster object
  k8s:
    state: present
    definition: "{{ lookup('template', 'storagecluster.j2') }}"
  register: reg_storagecluster
  until: 
    - reg_storagecluster.result.status.state == "Ready" 
  retries: 20 # wait for 10 minutes (20 retries x 30 sec = 600 sec)
  delay: 30    
