- name: Create the StorageCluster object
  k8s:
    state: present
    definition: "{{ lookup('template', 'storagecluster.j2') }}"
  when: odf_use_local_storage == "false"

- name: Create the StorageCluster object
  k8s:
    state: present
    definition: "{{ lookup('template', 'localstoragecluster.j2') }}"
  when: odf_use_local_storage == "true"

- name: Wait for ODF Storage Cluster Instance to be ready
  k8s_info:
    api_version: ocs.openshift.io/v1
    kind: StorageCluster
    name: ocs-storagecluster
    namespace: openshift-storage
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: reg_storagecluster
  until: reg_storagecluster.resources[0].status.phase is defined and reg_storagecluster.resources[0].status.phase == "Ready" 
  retries: 20 # wait for 10 minutes (20 retries x 30 sec = 600 sec)
  delay: 30