---
# defaults file for ocs-local-volume

default_storageclass: "ocs-storagecluster-cephfs"
odf_mcg_only: "{{ lookup('env', 'ODF_MCG_ONLY') | default('false', true) }}"
odf_mcg_storageclass: "{{ lookup('env', 'ODF_MCG_STORAGECLASS') | default('managed-nfs-storage', true) }}"
odf_enable_plugin: "{{ lookup('env', 'ODF_ENABLE_PLUGIN') | default('true', true) }}"
odf_fake: "{{ lookup('env', 'ODF_FAKE') | default('false', true) }}"
odf_use_local_storage: "{{ lookup('env', 'ODF_USE_LOCAL_STORAGE') | default('false', true) }}"
odf_storageclass: "{{ lookup('env', 'ODF_STORAGECLASS') | default('thin-csi', true) }}"
