galaxy_info:
  author: Eric Kleinsorgen (@ekleinso)
  description: Deploy MVI Edge Server
  company: IBM

  license: EPL-2.0

  min_ansible_version: 2.10

  platforms:
    - name: GenericLinux
      versions:
        - all

  galaxy_tags:
    - ibmce
    - ansible
    - ocp
    - mvie

dependencies:
  - role: ibmce.ocp_ansible.ansible_version_check

