---
# tasks file for cluster-logging

# The steps here try to mirror the steps described in the documenation page
# https://docs.openshift.com/container-platform/4.3/logging/cluster-logging-deploying.html
- name: Gather infra Nodes
  k8s_info:
    kind: Node
    label_selectors:
      - node-role.kubernetes.io/infra is defined
  register: infra_nodes
  
- name: Create openshift-operators-redhat Namespace
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/eo-namespace.yaml') | from_yaml }}"

- name: Create openshift-logging Namespace
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/clo-namespace.yaml') | from_yaml }}"

- name: Create OperatorGroup openshift-operators-redhat
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/eo-og.yaml') | from_yaml }}"

- name: Create OperatorGroup openshift-logging
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/clo-og.yaml') | from_yaml }}"

- name: Create Subscription for elasticsearch-operator
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/eo-sub.yaml') | from_yaml }}"

- name: Create necessary RBAC objects
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/eo-rbac.yaml') | from_yaml }}"

- name: Create Subscription for clusterlogging-operator
  k8s:
    state: present
    definition: "{{ lookup('file', '/files/clo-sub.yaml') | from_yaml }}"

- name: Wait for clusterlogging-operator subscription to be installed
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: openshift-logging
  register: reg_csr_status
  vars:
    status_query: "resources[*].status.phase"
    update_status: "{{ reg_csr_status | json_query(status_query) | flatten | unique }}"
  until:
    - update_status == ['Succeeded']
  retries: 10 # wait for 10 minutes (10 retries x 60 sec = 600 sec)
  delay: 60
  # TODO: Refind the udpate_status condition we check. As of now it check to
  #       see if all the operators installed in the namespace have a status of
  #       Succeeded. Consider just checking the operator that we need installed

- name: Create ClusterLogging instance
  vars:
    use_infra_node: "{{ true if (infra_nodes|length > 0) else false }}"
  k8s:
    state: present
    definition: "{{ lookup('template', 'clusterlogging.yaml.j2') }}"
