- name: Create ServiceAccount
  k8s:
    state: present
    definition: "{{ lookup('template', 'serviceaccount.yaml.j2') }}"
  register: reg_etcd_sa

- name: get privileged SecurityContext Object
  k8s_info:
    api_version: security.openshift.io/v1
    kind: SecurityContextConstraints
    name: privileged
  register: reg_privileged

- name: Grant privileged role to the backup user
  command: "oc adm policy add-scc-to-user privileged {{ etcd_backup_user }}"
  when:
    - reg_etcd_sa.changed
# Commenting out the original condiation as it doesn't seem to be working.
# and was breaking idempotentcy.
#    - etcd_backup_user not in privileged_users
  vars:
    privileged_users: "{{ reg_privileged.resources[0].users }}"

- name: get SecurityContext Object
  k8s_info:
    api_version: security.openshift.io/v1
    kind: SecurityContextConstraints
    name: anyuid
  register: reg_scc

- name: Grant anyuid scc role to the backup user
  command: "oc adm policy add-scc-to-user anyuid {{ etcd_backup_user }}"
  when:
    - reg_etcd_sa.changed
# Commenting out the original condiation as it doesn't seem to be working.
# and was breaking idempotentcy.
#    - etcd_backup_user not in scc_users
  vars:
    scc_users: "{{ reg_scc.resources[0].users }}"

# TODO: Need to investigate why the original when condition is not working any
#       more.
