---
# tasks file for lvm storage

- name: OC get upgrade channel
  shell:
    cmd: oc get clusterversion -o jsonpath='{.items[].spec.channel}{"\n"}'
  # Since this is a reporting task ...
  changed_when: false
  check_mode: false
  register: lvm_channel

- debug: var=lvm_channel

- name: Subscribe LVM Cluster Operator
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}') }}"
  loop:
    - "namespace.j2"
    - "OperatorGroup.j2"
    - "subscription.j2"

- name: Wait for LVM Cluster Operator to be installed
  k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: ClusterServiceVersion
    namespace: openshift-storage
    label_selectors:
      - operators.coreos.com/lvms-operator.openshift-storage
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: reg_csv_status
  until: 
    - reg_csv_status.resources[0].status.phase == "Succeeded" 
  retries: 20 # wait for 10 minutes (20 retries x 30 sec = 600 sec)
  delay: 30
  
- name: Deploy LVM Cluster resource
  k8s:
    state: present
    definition: "{{ lookup('template', 'lvmcluster.j2') }}"

- name: Wait for LVM Cluster to be Ready
  k8s_info:
    api_version: lvm.topolvm.io/v1alpha1
    kind: LVMCluster
    namespace: openshift-storage
    name: "{{ lvm_cluster }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: lvmcluster_status
  until: lvmcluster_status.resources[0].status.state is defined and lvmcluster_status.resources[0].status.state == "Ready"
  retries: 20 # wait for 10 minutes (20 retries x 30 sec = 600 sec)
  delay: 30
