---

- name: "Deploy fakesmtp"
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}') }}"
  loop:
    - "namespace.j2"
    - "deployment.j2"
    - "service.j2"
    - "route.j2"

- name: Wait for deployment
  k8s_info:
    api_version: apps/v1
    kind: Deployment
    namespace: "{{ fakesmtp_name }}"
    name: "{{ fakesmtp_name }}"
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: deployment_status
  until: deployment_status.resources[0].status.readyReplicas is defined and deployment_status.resources[0].status.readyReplicas == 1
  retries: 20 # wait for 10 minutes (20 retries x 30 sec = 600 sec)
  delay: 30

- name: "Configure Alertmanager"
  k8s:
    state: present
    definition: |
      kind: Secret
      apiVersion: v1
      metadata:
        name: alertmanager-main
        namespace: openshift-monitoring
      data:
        alertmanager.yaml: "{{ lookup('template', 'alertmanager.j2') | b64encode }}"
      type: Opaque
  when: fakesmtp_alertmanager == "true"