---
apiVersion: v1
kind: Secret
stringData:
  runner.sh: |
    pip3 install openshift pyyaml kubernetes passlib
    ansible-galaxy collection install git+https://github.com/ekleinso/ocp4-ansible-devops.git
    ansible-playbook post-deploy-playbook.yaml
  post-deploy-playbook.yaml: |
    ---
    - name: Configure Cluster
      gather_facts: no
      hosts: localhost
      vars:
        users:
        - name: "zeus"
          password: "Olympus"
        nfs_server: "192.168.1.66"
        nfs_path: "/nas/share"
        nfs_on_master: "true"
        odf_mcg_only: "true"
        odf_mcg_storageclass: "managed-nfs-storage"
        prometheus_retention_period: "24h"
        prometheus_storage_class: "managed-nfs-storage"
        gpu_timeslicing_enable: "true"
        gpu_timeslicing_config: "Nvidia-8"
        rhodsc_channel: "embedded"

      roles:
      - ibmce.ocp_ansible.admin_acks
      - ibmce.ocp_ansible.catalog_source
      - ibmce.ocp_ansible.htpasswd
      - ibmce.ocp_ansible.managed_nfs_storage
      - ibmce.ocp_ansible.odf_storage
      - ibmce.ocp_ansible.image_registry
      - ibmce.ocp_ansible.cluster_monitoring
      - ibmce.ocp_ansible.gpu
      - ibmce.ocp_ansible.rhodsc
metadata:
  name: post-deployment-scripts
  namespace: ibm-post-deployment
type: Opaque

