---
# defaults file for ntp
#
machine_config_suffix: "chrony-config"

machineconfigpools:
  - master
  - worker


ntp_servers: "{{ lookup('env', 'NTP_SERVERS').split(',') | default([], true) }}"

ntp_pools: "{{ lookup('env', 'NTP_POOLS').split(',') | default([], true) }}"

