---
# tasks file for nfs

- name: Prepare NFS Client Provisioner environment
  k8s:
    state: present
    definition: "{{ lookup('template', '{{ item }}') }}"
  loop:
    - "namespace.j2"
    - "scc.j2"
    - "StorageClass.j2"
    - "ServiceAccount.j2"
    - "ClusterRole.j2"
    - "ClusterRoleBinding.j2"
    - "role.j2"
    - "RoleBinding.j2"

- name: Deploy NFS Client Provisioner
  k8s:
    state: present
    definition: "{{ lookup('template', 'deployment.j2') }}"
    wait: true
    wait_sleep: 10
    wait_timeout: 600
    wait_condition:
      type: Available
      status: "True"
