---
# tasks file for ocp-nfs

# Only invoke the configure-nfs.yml tasks if the variable
# contains a NFS server and NFS path
- include_tasks: configure-nfs.yml
  when:
    - nfs_server and nfs_path

- include_tasks: configure-nfs-ganesha.yml
  when:
    - nfs_ganesha_storageclass

