- name: get PVC object
  k8s_info:
    api_version: v1
    kind: PersistentVolumeClaim
    name: "{{ etcd_backup_pvc_claim }}"
    namespace: "{{ etcd_backup_namespace }}"
  register: reg_etcd_backup_pvc

- name: Create PVC for use with the cron job
  k8s:
    state: present
    definition: "{{ lookup('template', 'etcd-backup-pvc.yaml.j2') }}"
  when:
    - not reg_etcd_backup_pvc.resources
