---

# 1. Provide debug information to the user
# -----------------------------------------------------------------------------
- name: "Debug information"
  debug:
    msg:
      - "Cluster ID ................... {{ etcd_cluster_id }}"
      - "Namespace .................... {{ etcd_backup_namespace }}"
      - "Service Account .............. {{ etcd_backup_username }}"
      - "Storage class ................ {{ etcd_backup_storageclass }}"
      - "PVC Name ..................... {{ etcd_backup_pvc_claim }}"
      - "Volume Size .................. {{ etcd_backup_volume_size }}"

# tasks file for etcd-backup

- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"

- include_tasks: serviceaccount.yml

- include_tasks: create-pvc.yml

- include_tasks: get_etcd_image.yml

- include_tasks: fetch_ocp_version.yml

# NOTE: Eg for OpenShift 4.5.2 We look for backup_script-4.5.2.sh first
#       if missing, we will look for backup_script-4.5.sh next.
#       When OpenShift 4.6 comes out we will need to have a new backup_script
#       added for 4.6. Also if in future OpenShift 4.5.10 come up with a
#       breaking change we can added backup_script-4.5.10.sh to overcome.
- include_tasks: configmap.yml
  vars:
    backup_scripts:
      - "backup_script-{{ ocp_version }}.sh"
      - "backup_script-{{ ocp_major_version }}.sh"
      - "etcd-snapshot-backup-disconnected.sh"
    etcd_backup_script: "{{ lookup('first_found', backup_scripts) }}"

- name: Create CronJob
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'cronjob.yaml.j2') }}"
