# Move the default Ingress Controller to the infra nodes
- name: Gather infra Nodes
  k8s_info:
    kind: Node
    label_selectors:
      - "node-role.kubernetes.io/infra"
  register: ocp_infra_nodes

- name: Search for default Ingress Controller
  k8s_info:
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
  register: reg_ocp_ingresscontroller

- set_fact:
    ingress_patch:
    - '{"nodePlacement":{"nodeSelector":{"matchLabels":{"node-role.kubernetes.io/infra":""},'
    - '{"tolerations":[{"key":"node-role.kubernetes.io/infra","operator":"Exists"}]}'
    - '}'
    - '}'
    - '}'

- name: Move the Ingress Controller to the Infra Nodes
  kubernetes.core.k8s_json_patch:
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    patch:
      - op: add
        path: /spec/nodePlacement
        value: {"nodeSelector":{"matchLabels":{"node-role.kubernetes.io/infra":""}}}
      - op: add
        path: /spec/nodePlacement/tolerations
        value: [{"key":"node-role.kubernetes.io/infra","operator":"Exists"}]
  when:
    - ocp_infra_nodes.resources
    - reg_ocp_ingresscontroller.resources[0].spec.nodePlacement.nodeSelector.matchLabels["node-role.kubernetes.io/infra"] is not defined
